-- ============================================================================
-- Banking Operations & Compliance Monitoring Platform
-- PostgreSQL Database Schema (Day 2)
-- ============================================================================

-- Drop tables if they exist (for development/iteration)
DROP TABLE IF EXISTS compliance_flags CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS branches CASCADE;

-- 1. Branches Table
CREATE TABLE branches (
    branch_id          VARCHAR(20) PRIMARY KEY,
    branch_name        VARCHAR(150) NOT NULL,
    city               VARCHAR(100),
    state              VARCHAR(50),
    zip_code           VARCHAR(20),
    phone              VARCHAR(50),
    branch_type        VARCHAR(50),
    opened_date        DATE,
    is_active          BOOLEAN DEFAULT TRUE,
    created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Customers Table
-- Stores core customer demographics and KYC (Know Your Customer) status.
CREATE TABLE customers (
    customer_id        VARCHAR(20) PRIMARY KEY,
    first_name         VARCHAR(100) NOT NULL,
    last_name          VARCHAR(100) NOT NULL,
    email              VARCHAR(150) UNIQUE NOT NULL,
    phone_number       VARCHAR(50),
    date_of_birth      DATE NOT NULL,
    address            VARCHAR(255),
    city               VARCHAR(100),
    state              VARCHAR(50),
    zip_code           VARCHAR(20),
    country            VARCHAR(50) DEFAULT 'USA',
    registration_date  DATE NOT NULL,
    customer_segment   VARCHAR(50) CHECK (customer_segment IN ('Retail', 'Premium', 'Business')),
    kyc_status         VARCHAR(50) CHECK (kyc_status IN ('Verified', 'Pending', 'Failed', 'Expired')),
    is_active          BOOLEAN DEFAULT TRUE,
    annual_income      NUMERIC(15, 2),
    occupation         VARCHAR(100),
    nationality        VARCHAR(100),
    created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Accounts Table
-- Links customers to their financial products at specific branches.
CREATE TABLE accounts (
    account_id         VARCHAR(20) PRIMARY KEY,
    customer_id        VARCHAR(20) REFERENCES customers(customer_id) ON DELETE CASCADE,
    branch_id          VARCHAR(20) REFERENCES branches(branch_id),
    account_type       VARCHAR(50) NOT NULL, -- e.g., Checking, Savings, Fixed Deposit
    account_status     VARCHAR(50) CHECK (account_status IN ('Active', 'Inactive', 'Frozen', 'Closed', 'Pending Review')),
    customer_segment   VARCHAR(50), -- Denormalized for reporting performance
    currency           CHAR(3) DEFAULT 'USD',
    opening_balance    NUMERIC(18, 2) DEFAULT 0.00,
    current_balance    NUMERIC(18, 2) DEFAULT 0.00,
    interest_rate      NUMERIC(5, 2),
    opened_at          DATE NOT NULL,
    credit_limit       NUMERIC(15, 2),
    overdraft_limit    NUMERIC(15, 2),
    created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. Transactions Table
-- Central fact table for all financial activity.
CREATE TABLE transactions (
    transaction_id         VARCHAR(20) PRIMARY KEY,
    account_id             VARCHAR(20) REFERENCES accounts(account_id) ON DELETE CASCADE,
    transaction_type       VARCHAR(50) NOT NULL,
    transaction_date       DATE NOT NULL,
    transaction_time       TIME NOT NULL,
    transaction_timestamp  TIMESTAMP NOT NULL,
    amount                 NUMERIC(18, 2) NOT NULL,
    currency               CHAR(3) DEFAULT 'USD',
    direction              VARCHAR(10) CHECK (direction IN ('Credit', 'Debit')),
    payment_method         VARCHAR(50),
    channel                VARCHAR(50), -- e.g., Online, ATM, Branch
    merchant_name          VARCHAR(150),
    merchant_category      VARCHAR(100),
    counterparty_account   VARCHAR(50),
    destination_country    VARCHAR(100),
    customer_segment       VARCHAR(50), -- Denormalized for analysis
    account_status_at_tx   VARCHAR(50), -- Behavioral snapshot
    status                 VARCHAR(50) NOT NULL, -- Completed, Failed, Pending
    failure_reason         VARCHAR(255),
    reference_number       VARCHAR(100),
    is_flagged             BOOLEAN DEFAULT FALSE,
    notes                  TEXT,
    created_at             TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 5. Compliance Flags Table
-- Stores alerts generated by the transaction monitoring system.
CREATE TABLE compliance_flags (
    flag_id             VARCHAR(100) PRIMARY KEY,
    transaction_id      VARCHAR(20) REFERENCES transactions(transaction_id) ON DELETE CASCADE,
    account_id          VARCHAR(20) REFERENCES accounts(account_id),
    rule_id             VARCHAR(50) NOT NULL,
    flag_reason         TEXT,
    risk_level          VARCHAR(20) CHECK (risk_level IN ('Low', 'Medium', 'High', 'Critical')),
    risk_score          INTEGER CHECK (risk_score BETWEEN 0 AND 100),
    customer_segment    VARCHAR(50),
    status              VARCHAR(50) CHECK (status IN ('Pending Review', 'Under Investigation', 'Cleared', 'Escalated', 'Reported to FinCEN')),
    analyst_assigned    VARCHAR(100),
    amount              NUMERIC(18, 2),
    destination_country VARCHAR(100),
    flagged_at          TIMESTAMP NOT NULL,
    resolved_at         TIMESTAMP,
    notes               TEXT,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- INDEXING STRATEGY (Optimization for Analytical Queries & Power BI)
-- ============================================================================

-- Indexes for performance on joins and common filter columns
CREATE INDEX idx_customers_segment ON customers(customer_segment);
CREATE INDEX idx_accounts_customer ON accounts(customer_id);
CREATE INDEX idx_accounts_branch   ON accounts(branch_id);
CREATE INDEX idx_accounts_status   ON accounts(account_status);

-- Time-series indexing for transaction analysis
CREATE INDEX idx_transactions_timestamp ON transactions(transaction_timestamp);
CREATE INDEX idx_transactions_date      ON transactions(transaction_date);
CREATE INDEX idx_transactions_account   ON transactions(account_id);
CREATE INDEX idx_transactions_type      ON transactions(transaction_type);
CREATE INDEX idx_transactions_amount    ON transactions(amount);

-- Compliance monitoring indexing
CREATE INDEX idx_compliance_rule     ON compliance_flags(rule_id);
CREATE INDEX idx_compliance_status   ON compliance_flags(status);
CREATE INDEX idx_compliance_risk     ON compliance_flags(risk_level);
CREATE INDEX idx_compliance_flagged_at ON compliance_flags(flagged_at);

-- ============================================================================
-- ANALYTICAL VIEWS (Power BI Preparation)
-- ============================================================================

-- View for Customer 360 Dashboard
CREATE OR REPLACE VIEW view_customer_profile AS
SELECT 
    c.customer_id,
    c.first_name || ' ' || c.last_name as full_name,
    c.customer_segment,
    c.kyc_status,
    c.is_active as customer_active,
    COUNT(a.account_id) as total_accounts,
    SUM(a.current_balance) as total_balance
FROM customers c
LEFT JOIN accounts a ON c.customer_id = a.customer_id
GROUP BY c.customer_id, c.first_name, c.last_name, c.customer_segment, c.kyc_status, c.is_active;

-- View for AML Risk Monitoring
CREATE OR REPLACE VIEW view_risk_alerts AS
SELECT 
    cf.flag_id,
    cf.rule_id,
    cf.risk_level,
    cf.risk_score,
    cf.status as flag_status,
    t.transaction_timestamp,
    t.amount,
    t.direction,
    t.destination_country,
    a.account_id,
    c.customer_segment
FROM compliance_flags cf
JOIN transactions t ON cf.transaction_id = t.transaction_id
JOIN accounts a ON cf.account_id = a.account_id
JOIN customers c ON a.customer_id = c.customer_id;
